// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/list-journal-entries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-journal-entries.ts
var list_journal_entries_default = defineTool({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List the signed-in trader's most recent trading log entries.",
  inputSchema: { limit: z.number().int().min(1).max(100).default(20).describe("Max entries to return.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("journal_entries").select("id, created_at, market_pair, result, pnl_pips, pnl_unit, session, mood, notes, tags").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/add-journal-entry.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var add_journal_entry_default = defineTool2({
  name: "add_journal_entry",
  title: "Add journal entry",
  description: "Log a new trade in the signed-in trader's trading log.",
  inputSchema: {
    market_pair: z2.string().trim().min(1).describe("Instrument, e.g. EURUSD or ES."),
    result: z2.enum(["win", "loss", "breakeven"]).optional().describe("Trade outcome."),
    pnl_pips: z2.number().optional().describe("Profit/loss amount."),
    notes: z2.string().max(5e3).optional().describe("Trade notes."),
    tags: z2.array(z2.string()).optional().describe("Performance tags.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("journal_entries").insert({ ...input, user_id: ctx.getUserId() }).select("id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Logged trade ${data.id}` }] };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.2";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in trader's TradersWorld profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xkhleosrspxxdhtgwaqg";
var mcp_default = defineMcp({
  name: "traders-world",
  title: "Traders World",
  version: "0.1.0",
  instructions: "Tools for TradersWorld, a trading accountability app. Use `get_my_profile` for the trader's profile, `list_journal_entries` to review their trading log, and `add_journal_entry` to log a trade.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_journal_entries_default, add_journal_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
